CONFIG_LOG=y
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_LORA=y
CONFIG_LORA_SX12XX=y
CONFIG_LORAWAN=y
CONFIG_LORAMAC_REGION_EU868=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_LORAWAN_NVM_SETTINGS=y

#CONFIG_LORAWAN_LOG_LEVEL_DBG=y
CONFIG_LORAWAN_FUOTA_LOG_LEVEL_DBG=y

CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y

#CONFIG_SETTINGS=y
#CONFIG_SETTINGS_RUNTIME=y
#CONFIG_SETTINGS_NVS=y
#CONFIG_ARM_MPU=n

CONFIG_LORAWAN_FUOTA=y

CONFIG_THREAD_NAME=y